### ISSUE TITLE
Missing Window Switching Feature

### ISSUE THREAD

**Issue by eret9616** [dexterleng/homerow#11]
I was using an old version homerow which is about 0.3?
when I updated to the latest, I find this app totally changed from "vimac-like"  to "spotlight-like",

in old homerow, press ctrl+w ,then I can move my cursor between apps, but the latest homerow or latest vimac doesn't support this feature

**Comment by eret9616** [comment]
https://install.appcenter.ms/users/dexterleng/apps/homerow/distribution_groups/released

**Comment by dexterleng** [comment]
Hi, @eret9616.

I'll be super honest - after using the feature for a bit I realised I don't like to use it personally and maintaining it was a chore. Perf is also a concern and hard to optimize. Hence I dropped the feature in the rebuild.

Personally I use contexts.co and recently switched to Raycast's window switching since Contexts doesn't support M1.

If you are keen on using the window switching feature, there is also Slate: https://github.com/jigish/slate

**Comment by bfulop** [comment]
> I use contexts.co and recently switched to Raycast's window switching since Contexts doesn't support M1.

Actually the latest beta of Contexts does support Apple Silicon natively! 🎉 

Can be downloaded from this page:

https://contexts.co/whats-new/

**Comment by dexterleng** [comment]
Closing this now!
