### ISSUE TITLE
App support: Mindnode

### ISSUE THREAD

**Issue by skobylite** [dexterleng/homerow#21]
I'd love to see support for mindnode in homerow! Their native search and filter is very trackpad-heavy :)

**Comment by dexterleng** [comment]
The non-canvas parts of Mindnode are labelled correctly:

![CleanShot 2022-12-28 at 14 48 22](https://user-images.githubusercontent.com/34204380/209770497-69904569-b622-476a-9239-5cabe44b0256.png)

There are no UI elements exposed through the Accessibility API for the canvas, except the focused text area. The Mindnode developers will have to support it. Consider dropping the developers an email.

https://www.mindnode.com/support

I'll close this issue because it's out of my hands.
