### ISSUE TITLE
Show typing progress in Labels

### ISSUE THREAD

**Issue by shogunsea** [dexterleng/homerow#30]
**Describe the bug**
OS: 13.1  M1 
Upper case letters are not showing up in the search bar, although they seems to be used in the search. 

**Screenshots / video**
In this case I typed `BC`, it finds the correct element but the search bar is empty. 
![homerow-casing-bug](https://user-images.githubusercontent.com/2238944/210268850-68eed7fc-126c-4827-bb55-e9ca684d5905.gif)

Add screenshots to help explain your problem. You can also use Loom to easily record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

**Comment by dexterleng** [comment]
@shogunsea I would like explain my mental model of this.

Search and Select are separate phases in the workflow.

The Search phase filters down the number of Labels shown on-screen.
The Select phase is used to focus on a single Label. This can be done via
  1. Arrow keys
  2. Typing Labels

Searching can only be done in lowercase, whereas Selecting via Labels can only be done via uppercase.

Because Labels are maximum of 3 characters long, I didn't see a point in capturing user input permanently. Hence the label input resets every 1 second. So actually have to type in the full label text in quick succession.

Does that make sense?

**Comment by shogunsea** [comment]
ah thanks for the explanation. This makes sense but still wasn't my initial expectation or intuition as a vimium user :) 
In vimium it just highlights whatever key currently being pressed so it's straightforward to see if user is selecting the right element:  (filtering all labels starting with `D`)
<img width="726" alt="image" src="https://user-images.githubusercontent.com/2238944/210433059-2d9a0fb1-7830-4c45-9497-dafe8527505e.png">

It'd be great to have similar visual indicator in homerow as well :)

**Comment by dexterleng** [comment]
@shogunsea oh yeah the "typed progress indicator" is def needed.

**Comment by shogunsea** [comment]
@dexterleng feel free to mark this closed as it's no longer blocking me! happy to provide more feedback whenever you have the progress indicator feature implemented

**Comment by dexterleng** [comment]
Retitled this issue :)

**Comment by dexterleng** [comment]
Addressed in Alpha 17: https://twitter.com/dexterleng/status/1623350101988233224/photo/3

Closing this now. Thanks!
