### ISSUE TITLE
Select text input without need for ENTER

### ISSUE THREAD

**Issue by jvican** [dexterleng/homerow#40]
**Is your feature suggestion related to a problem? Please describe.**
Despite my love for Homerow, I find myself not using it more often browsing (where I use Vimari/Vimium) because I need to click ENTER to confirm my label selection (when using classic mode). 

**Describe the solution you'd like**
It would be nice if Homerow had an option to disable the confirmation via ENTER, at least when selecting a text input. The idea would be that as soon as I type keys that match a label, it's selected. The cost of this is that if I mess the label up, I could be selecting the wrong thing. But that's rare enough for me that the speed of not having to click enter is worth it. 

**Describe alternatives you've considered**
We could also add an option like that not only for text inputs but any selection (including buttons). This would make it more similar to Vimium/Vimari.

**Comment by TheScriptan** [comment]
Vouching for this idea too. 

With Vimac I am saving one additional click whereas with Homerow `Return` needs to be pressed for each click that is wasteful.

**Comment by noamvokaal** [comment]
Me too. I’d love to bring that Vimac efficiency back.

**Comment by devnoname120** [comment]
Alternative: downgrade to [Homerow 0.3.7](https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/6ce6e2eb-ca43-4ffb-a557-dcd2edadd942/Homerow.dmg?sv=2019-02-02&sr=c&sig=burHJCc9B9qlWVTUNw961pWHZ%2BQolg%2BMNyrW0K2z65c%3D&se=2023-02-25T07%3A53%3A20Z&sp=r&download_origin=appcenter). It's the last version before Homerow became terrible.

**Comment by dexterleng** [comment]
@devnoname120 wow that's not nice 🙂

**Comment by dexterleng** [comment]
Anyways, this is really popular feedback - I'm working on this now :)

![CleanShot 2023-02-25 at 19 48 51](https://user-images.githubusercontent.com/34204380/221355241-c3abdf44-bc31-4205-9051-a626d91c8a64.png)

**Comment by jvican** [comment]
This is awesome @dexterleng, thanks for working on this. Please let me know if there's a release I can try out for early feedback. BTW, I love Homerow, and I'm thankful for your work on it. Keep it going! :+1:

**Comment by dexterleng** [comment]
# Auto-click Prototype

Here you go! Let me know your thoughts and if anything is broken. Double click stopped working for me last night but I am not able to replicate it today :/

Controls:
1. Left click: Type the label text as normal
2. Right click or Command Click: Type the label text while holding Shift or Command
3. Double click: Double press the last label character.

[homerow-auto-click.zip](https://github.com/dexterleng/homerow/files/10832959/homerow-auto-click.zip)

**Comment by noamvokaal** [comment]
Great work – thank you very much, @dexterleng! This did speed up my workflow a lot. The attached new version seems to interpret a lot of non-links as links, thus showing hints next to plain text. I noticed this behaviour mostly in browsers (Safari 
 & Brave) and in the macOS Mail app.


![Skärmavbild 2023-02-26 kl  12 05 09](https://user-images.githubusercontent.com/76404963/221406856-1b44a0e6-2944-4d43-9ec1-b1fd85b0f24e.png)

**Comment by dexterleng** [comment]
@noamvokaal It's like this even in previous versions. I could offer a "Fast or Exhaustive" option.

**Comment by jvican** [comment]
It'd be nice if we can map different shortcuts to each of those options. I like the fast vs slow heuristic, it's a good bump-up in UX if there's not an easy performant way of getting fine-grained labels.

**Comment by devnoname120** [comment]
@dexterleng Could there be an option so that it displays the “Fast” hints first and then computes the additional “Exhaustive” hints? This would provide the best of both worlds.

**Comment by devnoname120** [comment]
@dexterleng Sorry for the tone of my previous comment. I'm an early user who paid for Homerow at that time only in order to support you. Since then, I made two short emails with constructive feedback (as encouraged in Homerow) but I never heard back — hence my frustration.

I genuinely appreciate Homerow but it's unclear to me why so much effort was spent in rebuilding it (I think twice?) with unclear benefits for the end user, and actually even less features[1].

[1] The search-by-text workflow is very awkward because lots of buttons don't have text. Using the toolbox every time is a hassle and productivity-killer. Additionally, typing strings of text rather than hints is slower and error-prone — with hints you only need to press 2-3 characters so you can make sure to press the right ones. But with search-by-text you need to type way longer strings, so you type them faster and easily do typos which makes clicking a button frustrating.

**Comment by dexterleng** [comment]
@devnoname120 Apologies, I just saw your email from September. Let me know if that is still an issue with the new Homerow. 

I knew that the search workflow would be really polarizing - lots of Homerow user's used it to reduce the no. of keystrokes typed. But personally I prefer it in non-web apps with toolbars and other static buttons I can search and click without waiting for labels to show up or having to visually parse out the labels. Different strokes for different folks. Anyways, I'm working on bringing back Vimium-style navigation now. Let me know what you think!

**Comment by dexterleng** [comment]
@jvican @noamvokaal @TheScriptan @burgessa23 @robinhoutevelts

Any feedback on auto-click? Any bugs so far?

**Comment by noamvokaal** [comment]
> Any feedback on auto-click? Any bugs so far?

The new version has worked like a charm. I haven’t encountered any bugs related to the change. I’m delighted!



> > It'd be nice if we can map different shortcuts to each of those options. I like the fast vs slow heuristic, it's a good bump-up in UX if there's not an easy performant way of getting fine-grained labels.
> 
> I don't think I'll offer multiple shortcuts for fast vs exhaustive. Because what if users want a separate shortcut for search vs no-search? Then there would be 4 types of shortcuts.

What about tabbing between the fast and exhaustive modes? (I know tab is used to navigate through clickable elements right now ... but something along those lines.) At the moment some apps are cluttered with hints, and that does decrease the visibility of buttons. At the same time the fast mode is mostly sufficient.

`shortcut` -> defaults to fast mode (if insufficient –> `tab` –> refreshing to exhaustive mode)

The same approach could be used for selection of search and hint modes. In that case users can switch between all four modes with only one shortcut and two other keypresses. The only alternatives in preferences would be what modes Homerow defaults to: hint/search and fast/exhaustive.

`.` and `,` are two available buttons for navigating between the modes. They’re close to homerow and not used otherwise.

**Comment by jvican** [comment]
No bugs so far; everything works like a charm!

+1 on tabbing between the fast and exhaustive modes. Seems to me like an intuitive way of solving the issue.

**Comment by burgessa23** [comment]
Working well so far!

**Comment by burgessa23** [comment]
Hi, checking to see if this got promoted to the release build? looks like that's currently 0.18

**Comment by dexterleng** [comment]
Just released Alpha 19. You'll need to enable the "Click automatically when label is selected" option.

![CleanShot 2023-04-07 at 17 58 08](https://user-images.githubusercontent.com/34204380/230589043-5d265fef-c75a-41b0-b6dc-56b8a6d59c3c.png)

Let me know if there's any issues!

**Comment by devnoname120** [comment]
@dexterleng I just tried the latest version of Homerow and I really like it! Thanks for the improvements :)
