### ISSUE TITLE
Does not support BBEdit

### ISSUE THREAD

**Issue by ChristinWhite** [dexterleng/homerow#47]
Unfortunately, Homerow doesn't seem to play nicely with [BBEdit](https://www.barebones.com/products/bbedit/). This is one of those essential apps for me so I'd love to see support added!

**Comment by dexterleng** [comment]
Where isn't it working for you? The toolbar below the window title isn't accessible so Homerow can't find anything :(

![CleanShot 2023-04-07 at 16 50 27](https://user-images.githubusercontent.com/34204380/230577150-f32daa4c-28a0-4adc-a27a-551e7a741158.png)

![CleanShot 2023-04-07 at 16 50 34](https://user-images.githubusercontent.com/34204380/230577163-637284ee-8e5b-47af-afb6-4300585af525.png)

**Comment by noamvokaal** [comment]
> Where isn't it working for you? The toolbar below the window title isn't accessible so Homerow can't find anything :(

@dexterleng: Homerow does not find the checkboxes and buttons in the search window in BBEdit. That’s my main concern. Would that be possible to fix?

![Skärmavbild 2023-04-13 kl  13 30 24](https://user-images.githubusercontent.com/76404963/231745607-c74a6155-4979-4b45-a8cd-836e46af4b37.png)

**Comment by dexterleng** [comment]
Nope. If you used Accessibility Inspector you can see it's not possible to find the buttons. The BBEdit developers will have to make it accessible on their end.

![CleanShot 2023-04-15 at 13 46 56](https://user-images.githubusercontent.com/34204380/232186969-f555a30a-a06a-4e5f-a493-aa01f8b27b14.png)

Closing this since it is out of my hands.
