### ISSUE TITLE
Cannot target the Node Debugger icon in Chrome Devtools

### ISSUE THREAD

**Issue by amacdougall** [dexterleng/homerow#55]
At the upper left of the Chrome Devtools is a little hexagon icon which lights up green when a nodejs application is running in debug mode. Clicking this button brings up a dedicated Node debugger. I would love to be able to hit this button with Homerow! But I know it's very obscure.

Homerow's Tutor feature doesn't show any info for it, so this button might be beyond the reach of the APIs Homerow is using. Feel free to close as "can't fix" if so.

The button in question:

![Screenshot 2023-04-08 at 3 35 51 PM](https://user-images.githubusercontent.com/592916/230739622-f6c3d18c-cf28-4604-9304-3a387671c5c9.png)

With Homerow activated:

![Screenshot 2023-04-08 at 3 36 34 PM](https://user-images.githubusercontent.com/592916/230739647-b54ba98e-7d87-45b7-9496-9b9a4ba87b92.png)

Expected behavior: the little green hexagon gets a shortcut as well.

### Repro steps:

1. Run a node application with `node --inspect` (see appendix)
2. Open Chrome devtools in any browser window
3. Try to use Homerow to hit the little green hexagon

### Appendix

Not a node guy? Ultra minimal app setup:

```bash
mkdir node-test
cd node-test
npm init --yes
npm install express
```
Create an `app.js` with this content:
```javascript
const express = require("express");

const app = express();

app.get('/', (_, res) => {
  res.statusCode = 200;
  res.send("hello world!");
});

app.listen(3000, () => 'Server started.');
```
Back in the terminal:
```bash
node --inspect app.js
```

This is not a critical request. I have a macro program I can configure to find and click that button by recognizing the bitmap. But why go through the trouble?

Homerow is great anyway—just bought a license.

**Comment by dexterleng** [comment]
Hi @amacdougall. That's because the node button isn't recognized as a clickable Accessibility UI element. I'm not sure where the Issues page for the node plugin is, but you can let the developers know to make this button accessible.

Using the Accessibility Inspector on Xcode, notice that the buttons beside the node button are `toggle buttons` and support the `AXPress` action:
![CleanShot 2023-04-09 at 14 21 15](https://user-images.githubusercontent.com/34204380/230757919-9fe1541d-aa10-4efe-93dc-e90d436e7bee.png)

However the Node button is a `group` element and does not support an action that would indicate it is clickable, so the Homerow algorithm filters it out.
![CleanShot 2023-04-09 at 14 20 59](https://user-images.githubusercontent.com/34204380/230757967-aa1b2b27-d731-418e-a6b7-2cedb8443a8d.png)

**Comment by amacdougall** [comment]
Thanks! I figured it was something like that. I appreciate the quick response.
